# Generated by Django 5.2.10 on 2026-01-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(to='mailing.recipient'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
