# Generated by Django 5.2.10 on 2026-01-18 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_recipients_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailing.recipient'),
            preserve_default=False,
        ),
    ]
