# Generated by Django 5.2.10 on 2026-01-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_attempt_recipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('view_all_mailings', 'Может просматривать все рассылки'), ('disable_mailings', 'Может отключать рассылки')]},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('view_all_messages', 'Может просматривать все сообщения')]},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'permissions': [('view_all_recipients', 'Может просматривать всех получателей')]},
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
